// Package datafusion embeds the Apache DataFusion query engine in Go via a
// thin C ABI (see include/datafusion_go.h) implemented by the Rust staticlib
// under rust/datafusion-c-abi.
package datafusion

/*
#cgo CFLAGS: -I${SRCDIR}/../include
#cgo LDFLAGS: ${SRCDIR}/../rust/target/release/libdatafusion_c_abi.a
#cgo darwin LDFLAGS: -lresolv -framework Security -framework CoreFoundation -lpthread -ldl -lm
#cgo linux LDFLAGS: -lpthread -ldl -lm
#include <stdlib.h>
#include "datafusion_go.h"
*/
import "C"

import (
	"errors"
	"unsafe"

	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/cdata"
)

// sessionHandle is the opaque engine-side session handle, boxed on the Rust
// side and passed across the FFI boundary as a raw pointer.
type sessionHandle = C.df_session_t

// cErrorToGo converts a C error string returned by the Rust library into a
// Go error, freeing the C string in the process. Returns nil if cErr is
// NULL.
func cErrorToGo(cErr *C.char) error {
	if cErr == nil {
		return nil
	}
	defer C.df_string_free(cErr)
	return errors.New(C.GoString(cErr))
}

// sessionNew creates a new engine-side session, returning its opaque handle.
func sessionNew() (sessionHandle, error) {
	var cErr *C.char
	handle := C.df_session_new((**C.char)(unsafe.Pointer(&cErr)))
	if err := cErrorToGo(cErr); err != nil {
		return nil, err
	}
	if handle == nil {
		return nil, errors.New("datafusion: session creation failed with no error message")
	}
	return handle, nil
}

// sessionFree releases the engine-side session and all resources it owns.
func sessionFree(handle sessionHandle) {
	C.df_session_free(handle)
}

// sessionSQL executes sql on the session and returns a RecordReader over the
// result, importing the Arrow C Stream the engine writes the result into.
// Data crosses the FFI boundary zero-copy.
func sessionSQL(handle sessionHandle, sql string) (array.RecordReader, error) {
	cSQL := C.CString(sql)
	defer C.free(unsafe.Pointer(cSQL))

	var cStream C.struct_ArrowArrayStream
	cErr := C.df_session_sql(handle, cSQL, &cStream)
	if err := cErrorToGo(cErr); err != nil {
		return nil, err
	}

	// cStream and cdata's own C.struct_ArrowArrayStream are distinct Go
	// types generated by separate cgo compilation units, but both conform
	// to the same standard Arrow C Stream Interface layout, so the pointer
	// can be reinterpreted safely.
	reader, err := cdata.ImportCRecordReader((*cdata.CArrowArrayStream)(unsafe.Pointer(&cStream)), nil)
	if err != nil {
		return nil, err
	}
	recordReader, ok := reader.(array.RecordReader)
	if !ok {
		return nil, errors.New("datafusion: imported stream reader does not implement array.RecordReader")
	}
	return recordReader, nil
}
